### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Cosmas47** [michaelbarlow7/moonbase-console#2]
Mihcael, I have some questions about the HE3 / HE4 format. How can I contact you or SpacemanSpiff ?

**Comment by michaelbarlow7** [comment]
Hey Cosmas!

I don't really know much about the format of those files myself unfortunately. I do have the details of MYCROFT who was involved in the original development of MBC, would that help?

**Comment by Cosmas47** [comment]
Sure thing, I appreciate it. CosmasA@gmail.com
